[package]
name = "solana_whale_trader"
version = "0.1.0"
edition = "2021"

[dependencies]
# Async runtime
tokio = { version = "1.28", features = ["full"] }
# Solana SDK
solana-sdk = "2.1.11"
solana-client = "2.1.11"
solana-program = "2"
# HTTP client
reqwest = { version = "0.12.12", features = ["json"] }
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Logging
log = "0.4"
env_logger = "0.11.6"
# Error handling
thiserror = "2.0.11"
# Date/Time
chrono = { version = "0.4", features = ["serde"] }
lru = "0.12"
futures = "0.3"
dotenv = "0.15"
solana-transaction-status = "1.17"
rust_decimal = { version = "1.31", features = ["maths"] }
num-traits = "0.2"

[dev-dependencies]
mockall = "0.13.1"
lru = "0.12.1"